name: Nightly Build

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dotnetcore
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8'

      - name: Restore dependencies
        run: dotnet restore "VideoWallpaper.sln"

      - name: Publish project
        run: |
          dotnet publish "VideoWallpaper.csproj" `
            --configuration Release `
            --runtime win-x64 `
            -p:Platform=x64 `
            --output ./publish

      - name: Archive production assets
        run: Compress-Archive -Path ./publish/* -DestinationPath VideoWallpaper-nightly.zip

      - name: Create or Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          body: |
            🧪 Automated nightly build. This release is updated frequently and may be unstable.

            **重要:** 运行此程序前，您必须先在您的 Windows 电脑上安装 [.NET 8 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/8.0/runtime?runtime=desktop)。

            - 视频文件请放置于wallpaper文件夹。
          prerelease: true
          files: VideoWallpaper-nightly.zip
